### PR TITLE
Add git client function for retrieving the current branch name

### PR DESCRIPTION
**Pull request by costinsin**

### CODE REVIEW

**Comment by costinsin** [comment]
* **#16** <a href="https://app.graphite.dev/github/pr/costinsin/gi/16?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @costinsin and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by RazvanDire — APPROVED** [review]
Should we always check the exit code of a command before trying to parse its output? Or was this a more particular case

**Comment by costinsin** [comment]
I think so. If not, the stdout will be an empty Vec<u8>, so you won't have a clue if the command failed or not.

In this case, the command fails (returns 1) if the HEAD is not checked out on a branch so I had to account for this.

**Comment by costinsin** [comment]
### Merge activity

* **May 2, 4:52 AM EDT**: @costinsin started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/costinsin/gi/16).
* **May 2, 4:52 AM EDT**: @costinsin merged this pull request with [Graphite](https://app.graphite.dev/github/pr/costinsin/gi/16).

**Pull request merged**
